@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "u:DeleteTimeCommand" as DeleteTimeCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(deleteTime)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(deleteTime)
activate AddressBookParser

create DeleteTimeCommand
AddressBookParser -> DeleteTimeCommand
activate DeleteTimeCommand

DeleteTimeCommand --> AddressBookParser
deactivate DeleteTimeCommand

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> DeleteTimeCommand : execute()
activate DeleteTimeCommand

DeleteTimeCommand -> Model : setPerson()
activate Model

Model --> DeleteTimeCommand
deactivate Model

DeleteTimeCommand --> LogicManager : result
deactivate DeleteTimeCommand
DeleteTimeCommand -[hidden]-> LogicManager : result
destroy DeleteTimeCommand

[<--LogicManager
deactivate LogicManager
@enduml
