@startuml
'https://plantuml.com/class-diagram

interface Logic {
+execute(String): CommandResult
+getAddressBook(): ReadOnlyAddressBook
+getFilteredPersonList(): ObservableList<Person>
+getAddressBookFilePath(): Path
+getGuiSettings(): GuiSettings
+setGuiSettings(GuiSettings)
}

class LogicManager implements Logic {
}


interface ReadOnlyUserPrefs {
+getGuiSettings(): GuiSettings
+getAddressBookFilePath(): Path
}

class UserPrefs {
-guiSettings: GuiSettings
-addressBookFilePath: Path

+resetData(ReadOnlyUserPrefs)
+setGuiSettings(GuiSettings)
+setAddressBookFilePath(Path)
+getAddressBookFilePath(): Path
}

ReadOnlyUserPrefs <|.. UserPrefs

interface Model {
+PREDICATE_SHOW_ALL_PERSONS: Predicate<Person>

+hasPerson(Person): boolean
+deletePerson(Person)
+addPerson(Person)
+removePerson(Person)
+getPersonList(): ObservableList<Person>
+setPerson(target: Person, editedPerson: Person)
}

class ModelManager {
-logger: Logger
-addressBook: AddressBook
-userPrefs: UserPrefs
-filteredPersons: FilteredList<Person>
}

Model <|.. ModelManager

interface ReadOnlyAddressBook {
+getPersonList(): ObservableList<Person>
}

class AddressBook {
-persons: UniquePersonList

+setPersons(List<Person>)
+resetData(ReadOnlyAddressBook)
+addPerson(Person)
+hasPerson(Person): boolean
+setPerson(target: Person, editedPerson: Person)
}

ReadOnlyAddressBook <|.. AddressBook

class Person {

+isSamePerson(Person): boolean
+equals(Object): boolean
}

AddressBook "1" *-- "*" Person : contains

class Birthday {
+value: LocalDate

{static} +isValidBirthday(String): boolean
+isBirthday(): boolean
}

Person "1" *-- "1" Birthday

class Email {
+value: String

{static} +isValidEmail(String): boolean
}

Person "1" *-- "1" Email

abstract class Tag {
+tagName: String

{abstract} +equals(Object) : boolean
{abstract} +hashCode() : int
{abstract} +toString() : String
}

class DormTag extends Tag {
{static} +isValidTagName(String): boolean
}

Person "1" *-- "1" DormTag

class FreeTimeTag extends Tag {
-day: String
-startTime: String
-endTime: String


{static} +isValidTimeInterval(String): boolean
{static} +isValidTagName(String): boolean
}

Person "1" *-- "*" FreeTimeTag

class Name {
+value: String

{static} +isValidName(String): boolean
}

Person "1" *-- "1" Name

class Phone {
+value: String

{static} +isValidPhone(String): boolean
}

Person "1" *-- "1" Phone

class RoomNumber {
-block: String
-floor: String
-roomNumber: String
-lastModified: LocalDate

{static} +isValidRoomNumber(String): boolean
{static} +isValidRoomNumberWDate(String): boolean
{static} +isValidDate(String): boolean
+isOutdated(): boolean
+toString(): String
+toStringWDate(): String
}

Person "1" *-- "1" RoomNumber

class Telegram {
+value: String

{static} +isValidTelegram(String): boolean
}

Person "1" *-- "1" Telegram

interface Storage  {
+readUserPrefs(): Optional<UserPrefs>
+saveUserPrefs(ReadOnlyUserPrefs)
+getAddressBookFilePath(): Path
+readAddressBook():Optional<ReadOnlyAddressBook>
saveAddressBook(ReadOnlyAddressBook)
}

class CommandException extends Exception {
}

abstract class Command {
}

class AddCommand extends Command {
}

class ClearCommand extends Command {
}

class CommandResult extends Command {
}

class DeleteCommand extends Command {
}

class EditCommand extends Command {
}

class ExitCommand extends Command {
}

class FindCommand extends Command {
}

class HelpCommand extends Command {
}

class ListCommand extends Command {
}

class ParseException extends Exception {
}

class AddCommandParser implements Parser {
}

class AddressBookParser {
}

class ArgumentMultimap {
}

class ArgumentTokenizer {
}

class CliSyntax {
}

class DeleteCommandParser implements Parser {
}

class EditCommandParser implements Parser {
}

class FindCommandParser implements Parser {
}

interface Parser<T extends Command> {
}

class ParserUtil {
}

class Prefix {
}


class Messages {
}

@enduml
